// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Event struct {
	ID        int64
	Kind      string
	Body      []byte
	Message   string
	CreatedAt time.Time
}
