// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const errorEvents = `-- name: ErrorEvents :many
SELECT id, kind, body, message, created_at FROM events
WHERE message ~* 'error'
ORDER BY created_at DESC
`

func (q *Queries) ErrorEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, errorEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Body,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventEpochs = `-- name: EventEpochs :many
SELECT id, extract(epoch FROM created_at)::bigint AS epoch
FROM events
ORDER BY id
`

type EventEpochsRow struct {
	ID    int64
	Epoch int64
}

// sqlc infers `extract(epoch FROM …)` as numeric (matching real PG),
// but pgmem-go's date_part returns int8 today — the type clash makes
// the generated scan fail. Cast to bigint so both sides agree.
func (q *Queries) EventEpochs(ctx context.Context) ([]EventEpochsRow, error) {
	rows, err := q.db.Query(ctx, eventEpochs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventEpochsRow
	for rows.Next() {
		var i EventEpochsRow
		if err := rows.Scan(&i.ID, &i.Epoch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsByKindField = `-- name: EventsByKindField :many
SELECT id, body ->> 'user_id' AS user_id, message
FROM events
WHERE kind = $1
ORDER BY created_at DESC
LIMIT $2
`

type EventsByKindFieldParams struct {
	Kind  string
	Limit int32
}

type EventsByKindFieldRow struct {
	ID      int64
	UserID  interface{}
	Message string
}

func (q *Queries) EventsByKindField(ctx context.Context, arg EventsByKindFieldParams) ([]EventsByKindFieldRow, error) {
	rows, err := q.db.Query(ctx, eventsByKindField, arg.Kind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsByKindFieldRow
	for rows.Next() {
		var i EventsByKindFieldRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsByPayloadKey = `-- name: EventsByPayloadKey :many
SELECT id, kind, body, message, created_at FROM events
WHERE body @> $1::jsonb
ORDER BY created_at
`

func (q *Queries) EventsByPayloadKey(ctx context.Context, dollar_1 []byte) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventsByPayloadKey, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Body,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsPerHour = `-- name: EventsPerHour :many
SELECT date_trunc('hour', created_at)::timestamptz AS hour,
       count(*) AS n
FROM events
GROUP BY date_trunc('hour', created_at)
ORDER BY hour
`

type EventsPerHourRow struct {
	Hour time.Time
	N    int64
}

func (q *Queries) EventsPerHour(ctx context.Context) ([]EventsPerHourRow, error) {
	rows, err := q.db.Query(ctx, eventsPerHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsPerHourRow
	for rows.Next() {
		var i EventsPerHourRow
		if err := rows.Scan(&i.Hour, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :one

INSERT INTO events (kind, body, message, created_at)
VALUES ($1, $2, $3, $4) RETURNING id, kind, body, message, created_at
`

type RecordEventParams struct {
	Kind      string
	Body      []byte
	Message   string
	CreatedAt time.Time
}

// Exercises: jsonb @> and ->>; date_trunc + EXTRACT; regex match on
// the message column.
func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, recordEvent,
		arg.Kind,
		arg.Body,
		arg.Message,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Body,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
