// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       int64
	ParentID pgtype.Int8
	Name     string
}

type Product struct {
	ID         int64
	CategoryID int64
	Name       string
	Threshold  int32
}

type StockTxn struct {
	ID          int64
	ProductID   int64
	WarehouseID int64
	Delta       int32
	OccurredAt  time.Time
}

type Warehouse struct {
	ID   int64
	Name string
}
