// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addCategory = `-- name: AddCategory :one

INSERT INTO categories (parent_id, name) VALUES ($1, $2) RETURNING id, parent_id, name
`

type AddCategoryParams struct {
	ParentID *int64
	Name     string
}

// Exercises: sum() GROUP BY for on-hand; CTEs for per-warehouse
// rollup; CASE WHEN for low-stock flagging; self-referential FK on
// categories.
func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, addCategory, arg.ParentID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.ParentID, &i.Name)
	return i, err
}

const addProduct = `-- name: AddProduct :one
INSERT INTO products (category_id, name, threshold)
VALUES ($1, $2, $3) RETURNING id, category_id, name, threshold
`

type AddProductParams struct {
	CategoryID int64
	Name       string
	Threshold  int32
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, addProduct, arg.CategoryID, arg.Name, arg.Threshold)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Threshold,
	)
	return i, err
}

const addWarehouse = `-- name: AddWarehouse :one
INSERT INTO warehouses (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) AddWarehouse(ctx context.Context, name string) (Warehouse, error) {
	row := q.db.QueryRow(ctx, addWarehouse, name)
	var i Warehouse
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const childCategories = `-- name: ChildCategories :many
SELECT id, parent_id, name FROM categories WHERE parent_id = $1 ORDER BY name
`

func (q *Queries) ChildCategories(ctx context.Context, parentID *int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, childCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.ParentID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockReport = `-- name: LowStockReport :many
WITH on_hand AS (
    SELECT product_id, sum(delta)::int AS qty
    FROM stock_txns
    GROUP BY product_id
)
SELECT p.id, p.name,
       coalesce(o.qty, 0) AS qty,
       CASE WHEN coalesce(o.qty, 0) < p.threshold THEN 'low' ELSE 'ok' END AS status
FROM products p
LEFT JOIN on_hand o ON o.product_id = p.id
ORDER BY status, p.name
`

type LowStockReportRow struct {
	ID     int64
	Name   string
	Qty    int32
	Status string
}

func (q *Queries) LowStockReport(ctx context.Context) ([]LowStockReportRow, error) {
	rows, err := q.db.Query(ctx, lowStockReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LowStockReportRow
	for rows.Next() {
		var i LowStockReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Qty,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onHandByProduct = `-- name: OnHandByProduct :many
SELECT product_id, sum(delta)::int AS qty
FROM stock_txns
GROUP BY product_id
ORDER BY product_id
`

type OnHandByProductRow struct {
	ProductID int64
	Qty       int32
}

func (q *Queries) OnHandByProduct(ctx context.Context) ([]OnHandByProductRow, error) {
	rows, err := q.db.Query(ctx, onHandByProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnHandByProductRow
	for rows.Next() {
		var i OnHandByProductRow
		if err := rows.Scan(&i.ProductID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTxn = `-- name: RecordTxn :one
INSERT INTO stock_txns (product_id, warehouse_id, delta, occurred_at)
VALUES ($1, $2, $3, $4) RETURNING id, product_id, warehouse_id, delta, occurred_at
`

type RecordTxnParams struct {
	ProductID   int64
	WarehouseID int64
	Delta       int32
	OccurredAt  time.Time
}

func (q *Queries) RecordTxn(ctx context.Context, arg RecordTxnParams) (StockTxn, error) {
	row := q.db.QueryRow(ctx, recordTxn,
		arg.ProductID,
		arg.WarehouseID,
		arg.Delta,
		arg.OccurredAt,
	)
	var i StockTxn
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.WarehouseID,
		&i.Delta,
		&i.OccurredAt,
	)
	return i, err
}

const warehouseRollup = `-- name: WarehouseRollup :many
SELECT warehouse_id, sum(delta)::int AS qty
FROM stock_txns
GROUP BY warehouse_id
ORDER BY warehouse_id
`

type WarehouseRollupRow struct {
	WarehouseID int64
	Qty         int32
}

func (q *Queries) WarehouseRollup(ctx context.Context) ([]WarehouseRollupRow, error) {
	rows, err := q.db.Query(ctx, warehouseRollup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseRollupRow
	for rows.Next() {
		var i WarehouseRollupRow
		if err := rows.Scan(&i.WarehouseID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
