// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Item struct {
	ID        int64
	ListID    int64
	Title     string
	Done      bool
	DueAt     *time.Time
	CreatedAt time.Time
	DeletedAt *time.Time
}

type List struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	DeletedAt *time.Time
}
