// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const activeLists = `-- name: ActiveLists :many
SELECT id, name, created_at, deleted_at FROM lists WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ActiveLists(ctx context.Context) ([]List, error) {
	rows, err := q.db.Query(ctx, activeLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addItem = `-- name: AddItem :one
INSERT INTO items (list_id, title, done, due_at, created_at)
VALUES ($1, $2, false, $3, $4)
RETURNING id, list_id, title, done, due_at, created_at, deleted_at
`

type AddItemParams struct {
	ListID    int64
	Title     string
	DueAt     **time.Time
	CreatedAt time.Time
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, addItem,
		arg.ListID,
		arg.Title,
		arg.DueAt,
		arg.CreatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Done,
		&i.DueAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const completeItem = `-- name: CompleteItem :exec
UPDATE items SET done = true WHERE id = $1
`

func (q *Queries) CompleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeItem, id)
	return err
}

const itemsDueWithin = `-- name: ItemsDueWithin :many
SELECT id, list_id, title, done, due_at, created_at, deleted_at FROM items
WHERE deleted_at IS NULL
  AND due_at IS NOT NULL
  AND due_at <= $1 + interval '1 day'
ORDER BY due_at
`

func (q *Queries) ItemsDueWithin(ctx context.Context, dollar_1 interface{}) ([]Item, error) {
	rows, err := q.db.Query(ctx, itemsDueWithin, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Title,
			&i.Done,
			&i.DueAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletion = `-- name: ListCompletion :many
SELECT list_id, bool_and(done) AS all_done, count(*) AS total
FROM items
WHERE deleted_at IS NULL
GROUP BY list_id
ORDER BY list_id
`

type ListCompletionRow struct {
	ListID  int64
	AllDone bool
	Total   int64
}

func (q *Queries) ListCompletion(ctx context.Context) ([]ListCompletionRow, error) {
	rows, err := q.db.Query(ctx, listCompletion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletionRow
	for rows.Next() {
		var i ListCompletionRow
		if err := rows.Scan(&i.ListID, &i.AllDone, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteList = `-- name: SoftDeleteList :exec
UPDATE lists SET deleted_at = $1 WHERE id = $2
`

type SoftDeleteListParams struct {
	DeletedAt **time.Time
	ID        int64
}

func (q *Queries) SoftDeleteList(ctx context.Context, arg SoftDeleteListParams) error {
	_, err := q.db.Exec(ctx, softDeleteList, arg.DeletedAt, arg.ID)
	return err
}

const upsertList = `-- name: UpsertList :one

INSERT INTO lists (id, name, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = excluded.name
RETURNING id, name, created_at, deleted_at
`

type UpsertListParams struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

// Exercises: ON CONFLICT DO UPDATE upsert; soft delete via
// `deleted_at IS NULL` filtering; timestamp + interval math; bool_and
// aggregate per list.
func (q *Queries) UpsertList(ctx context.Context, arg UpsertListParams) (List, error) {
	row := q.db.QueryRow(ctx, upsertList, arg.ID, arg.Name, arg.CreatedAt)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
