// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Message struct {
	ID       int64
	RoomID   int64
	AuthorID int64
	ParentID *int64
	Body     string
	SentAt   time.Time
}

type Room struct {
	ID   int64
	Name string
}

type Subscription struct {
	UserID int64
	RoomID int64
}

type SystemMessage struct {
	ID     int64
	RoomID int64
	Body   string
	SentAt time.Time
}

type User struct {
	ID   int64
	Name string
}
