// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addRoom = `-- name: AddRoom :one
INSERT INTO rooms (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) AddRoom(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, addRoom, name)
	var i Room
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const addUser = `-- name: AddUser :one

INSERT INTO users (name) VALUES ($1) RETURNING id, name
`

// Exercises: UNION ALL across user + system messages; EXISTS for
// subscription gating; self-join on messages for thread replies;
// LIMIT/OFFSET pagination.
func (q *Queries) AddUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, addUser, name)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const postMessage = `-- name: PostMessage :one
INSERT INTO messages (room_id, author_id, parent_id, body, sent_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, room_id, author_id, parent_id, body, sent_at
`

type PostMessageParams struct {
	RoomID   int64
	AuthorID int64
	ParentID *int64
	Body     string
	SentAt   time.Time
}

func (q *Queries) PostMessage(ctx context.Context, arg PostMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, postMessage,
		arg.RoomID,
		arg.AuthorID,
		arg.ParentID,
		arg.Body,
		arg.SentAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.SentAt,
	)
	return i, err
}

const postSystemMessage = `-- name: PostSystemMessage :one
INSERT INTO system_messages (room_id, body, sent_at)
VALUES ($1, $2, $3) RETURNING id, room_id, body, sent_at
`

type PostSystemMessageParams struct {
	RoomID int64
	Body   string
	SentAt time.Time
}

func (q *Queries) PostSystemMessage(ctx context.Context, arg PostSystemMessageParams) (SystemMessage, error) {
	row := q.db.QueryRow(ctx, postSystemMessage, arg.RoomID, arg.Body, arg.SentAt)
	var i SystemMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Body,
		&i.SentAt,
	)
	return i, err
}

const replyThread = `-- name: ReplyThread :many
SELECT m.id, m.body AS reply_body, m.sent_at,
       parent.body AS parent_body
FROM messages m
JOIN messages parent ON parent.id = m.parent_id
WHERE m.parent_id = $1 OR parent.id = $1
ORDER BY m.sent_at
`

type ReplyThreadRow struct {
	ID         int64
	ReplyBody  string
	SentAt     time.Time
	ParentBody string
}

func (q *Queries) ReplyThread(ctx context.Context, parentID *int64) ([]ReplyThreadRow, error) {
	rows, err := q.db.Query(ctx, replyThread, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplyThreadRow
	for rows.Next() {
		var i ReplyThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.ReplyBody,
			&i.SentAt,
			&i.ParentBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomFeed = `-- name: RoomFeed :many
SELECT m.id, m.body, m.sent_at, 'user' AS source
FROM messages m
WHERE m.room_id = $1
UNION ALL
SELECT s.id, s.body, s.sent_at, 'system' AS source
FROM system_messages s
WHERE s.room_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type RoomFeedParams struct {
	RoomID int64
	Limit  int32
	Offset int32
}

type RoomFeedRow struct {
	ID     int64
	Body   string
	SentAt time.Time
	Source string
}

func (q *Queries) RoomFeed(ctx context.Context, arg RoomFeedParams) ([]RoomFeedRow, error) {
	rows, err := q.db.Query(ctx, roomFeed, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomFeedRow
	for rows.Next() {
		var i RoomFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.SentAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribe = `-- name: Subscribe :exec
INSERT INTO subscriptions (user_id, room_id) VALUES ($1, $2)
ON CONFLICT (user_id, room_id) DO NOTHING
`

type SubscribeParams struct {
	UserID int64
	RoomID int64
}

func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) error {
	_, err := q.db.Exec(ctx, subscribe, arg.UserID, arg.RoomID)
	return err
}

const subscribedRooms = `-- name: SubscribedRooms :many
SELECT DISTINCT r.id, r.name FROM rooms r
JOIN subscriptions s ON s.room_id = r.id
WHERE s.user_id = $1
ORDER BY r.name
`

// The natural shape here is `WHERE EXISTS (SELECT 1 FROM
// subscriptions WHERE user_id = $1 AND room_id = r.id)`, but
// pgmem-go's EXISTS is uncorrelated only — the inner query can't
// reference the outer row. A DISTINCT join produces the same
// result and exercises JOIN + DISTINCT instead.
func (q *Queries) SubscribedRooms(ctx context.Context, userID int64) ([]Room, error) {
	rows, err := q.db.Query(ctx, subscribedRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
