// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Match struct {
	ID       int64
	PlayerID int64
	Region   string
	Score    int32
	PlayedAt time.Time
}

type Player struct {
	ID   int64
	Name string
}
