// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addPlayer = `-- name: AddPlayer :one

INSERT INTO players (name) VALUES ($1) RETURNING id, name
`

// Exercises window functions (row_number / rank), array parameters
// with ANY, array_agg per group, and FROM-position unnest.
func (q *Queries) AddPlayer(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, addPlayer, name)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const expandIDs = `-- name: ExpandIDs :many
SELECT u::bigint AS id
FROM unnest($1::bigint[]) AS u
ORDER BY u
`

// FROM-position unnest. Each parameter element becomes a row. The
// explicit ::bigint cast tells sqlc the projected column's type.
func (q *Queries) ExpandIDs(ctx context.Context, dollar_1 []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, expandIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playersByIDs = `-- name: PlayersByIDs :many
SELECT id, name FROM players
WHERE id = ANY($1::bigint[])
ORDER BY id
`

// Filters via `= ANY ($1::bigint[])`. The standard sqlc pattern for
// "find these N rows."
func (q *Queries) PlayersByIDs(ctx context.Context, dollar_1 []int64) ([]Player, error) {
	rows, err := q.db.Query(ctx, playersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankByScore = `-- name: RankByScore :many
SELECT player_id, score,
       rank() OVER (ORDER BY score DESC) AS rk
FROM matches
ORDER BY rk, player_id
`

type RankByScoreRow struct {
	PlayerID int64
	Score    int32
	Rk       int64
}

// rank() shares positions on ties.
func (q *Queries) RankByScore(ctx context.Context) ([]RankByScoreRow, error) {
	rows, err := q.db.Query(ctx, rankByScore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankByScoreRow
	for rows.Next() {
		var i RankByScoreRow
		if err := rows.Scan(&i.PlayerID, &i.Score, &i.Rk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMatch = `-- name: RecordMatch :one
INSERT INTO matches (player_id, region, score, played_at)
VALUES ($1, $2, $3, $4) RETURNING id, player_id, region, score, played_at
`

type RecordMatchParams struct {
	PlayerID int64
	Region   string
	Score    int32
	PlayedAt time.Time
}

func (q *Queries) RecordMatch(ctx context.Context, arg RecordMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, recordMatch,
		arg.PlayerID,
		arg.Region,
		arg.Score,
		arg.PlayedAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Region,
		&i.Score,
		&i.PlayedAt,
	)
	return i, err
}

const scoresArrayPerPlayer = `-- name: ScoresArrayPerPlayer :many
SELECT player_id, array_agg(score)::bigint[] AS scores
FROM matches
GROUP BY player_id
ORDER BY player_id
`

type ScoresArrayPerPlayerRow struct {
	PlayerID int64
	Scores   []int64
}

// array_agg collects every score per player in a single bigint[].
func (q *Queries) ScoresArrayPerPlayer(ctx context.Context) ([]ScoresArrayPerPlayerRow, error) {
	rows, err := q.db.Query(ctx, scoresArrayPerPlayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoresArrayPerPlayerRow
	for rows.Next() {
		var i ScoresArrayPerPlayerRow
		if err := rows.Scan(&i.PlayerID, &i.Scores); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topScoresByRegion = `-- name: TopScoresByRegion :many
SELECT region, player_id, score,
       row_number() OVER (PARTITION BY region ORDER BY score DESC, id) AS rn
FROM matches
ORDER BY region, rn
`

type TopScoresByRegionRow struct {
	Region   string
	PlayerID int64
	Score    int32
	Rn       int64
}

// One row per (region, rank position) with ties broken by id. Uses
// row_number() OVER (PARTITION BY region ORDER BY score DESC).
func (q *Queries) TopScoresByRegion(ctx context.Context) ([]TopScoresByRegionRow, error) {
	rows, err := q.db.Query(ctx, topScoresByRegion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopScoresByRegionRow
	for rows.Next() {
		var i TopScoresByRegionRow
		if err := rows.Scan(
			&i.Region,
			&i.PlayerID,
			&i.Score,
			&i.Rn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
