// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Comment struct {
	ID        int64
	PostID    int64
	AuthorID  int64
	Body      string
	CreatedAt time.Time
}

type Post struct {
	ID        int64
	AuthorID  int64
	Title     string
	Body      string
	Published bool
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Email     string
	Name      string
	CreatedAt time.Time
}
