// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const countCommentsPerPost = `-- name: CountCommentsPerPost :many
SELECT post_id, count(*) AS comment_count
FROM comments
GROUP BY post_id
ORDER BY post_id
`

type CountCommentsPerPostRow struct {
	PostID       int64
	CommentCount int64
}

func (q *Queries) CountCommentsPerPost(ctx context.Context) ([]CountCommentsPerPostRow, error) {
	rows, err := q.db.Query(ctx, countCommentsPerPost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCommentsPerPostRow
	for rows.Next() {
		var i CountCommentsPerPostRow
		if err := rows.Scan(&i.PostID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, author_id, body, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, author_id, body, created_at
`

type CreateCommentParams struct {
	PostID    int64
	AuthorID  int64
	Body      string
	CreatedAt time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, body, published, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, title, body, published, created_at
`

type CreatePostParams struct {
	AuthorID  int64
	Title     string
	Body      string
	Published bool
	CreatedAt time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Published,
		arg.CreatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, email, name, created_at
`

type CreateUserParams struct {
	Email     string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, author_id, title, body, published, created_at FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsForPost = `-- name: ListCommentsForPost :many
SELECT c.id, c.post_id, c.author_id, c.body, c.created_at, u.name AS author_name
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.post_id = $1
ORDER BY c.created_at
`

type ListCommentsForPostRow struct {
	ID         int64
	PostID     int64
	AuthorID   int64
	Body       string
	CreatedAt  time.Time
	AuthorName string
}

func (q *Queries) ListCommentsForPost(ctx context.Context, postID int64) ([]ListCommentsForPostRow, error) {
	rows, err := q.db.Query(ctx, listCommentsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsForPostRow
	for rows.Next() {
		var i ListCommentsForPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT id, author_id, title, body, published, created_at FROM posts WHERE author_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPostsByAuthor(ctx context.Context, authorID int64) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT p.id, p.title, p.body, p.created_at, u.name AS author_name
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.published = true
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32
	Offset int32
}

type ListPublishedPostsRow struct {
	ID         int64
	Title      string
	Body       string
	CreatedAt  time.Time
	AuthorName string
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPostsRow
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, created_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postWithCommentCount = `-- name: PostWithCommentCount :one
SELECT p.id, p.title,
       (SELECT count(*) FROM comments c WHERE c.post_id = p.id) AS comment_count
FROM posts p
WHERE p.id = $1
`

type PostWithCommentCountRow struct {
	ID           int64
	Title        string
	CommentCount int64
}

func (q *Queries) PostWithCommentCount(ctx context.Context, id int64) (PostWithCommentCountRow, error) {
	row := q.db.QueryRow(ctx, postWithCommentCount, id)
	var i PostWithCommentCountRow
	err := row.Scan(&i.ID, &i.Title, &i.CommentCount)
	return i, err
}

const publishPost = `-- name: PublishPost :one
UPDATE posts SET published = true WHERE id = $1 RETURNING id, author_id, title, body, published, created_at
`

func (q *Queries) PublishPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, publishPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}
